fix info command unsupported warning
aws-amplify/amplify-backend pull request #1093
Opened 2024-03-01 05:01 UTC by ykethan

## Problem

**Issue number, if available:**
closes: https://github.com/aws-amplify/amplify-backend/issues/1000

when using node versions such as node 21, the cdk info command shows

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                                      !!
!!  This software has not been tested with node v21.6.1.                                                                !!
!!  Should you encounter odd runtime issues, please try using one of the supported release before filing a bug report.  !!
!!                                                                                                                      !!
!!  This software is currently running on node v21.6.1.                                                                 !!
!!  As of the current release of this software, supported node releases are:                                            !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                                                                         !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                                                                         !!
!!                                                                                                                      !!
!!  This warning can be silenced by setting the JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION environment variable.        !!
!!                                                                                                                      !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

## Changes

**Corresponding docs PR, if applicable:**
add env variable to `JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION` this execa process to silence the warning

tested locally with node 21
<img width="434" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/87995712/9ec66206-2081-4bea-8ea0-449469cfb163">

## Validation

## Checklist

- [ ] If this PR includes a functional change to the runtime behavior of the code, I have added or updated automated test coverage for this change.
- [ ] If this PR requires a change to the [Project Architecture README](../PROJECT_ARCHITECTURE.md), I have included that update in this PR.
- [ ] If this PR requires a docs update, I have linked to that docs PR above.
- [ ] If this PR modifies E2E tests, makes changes to resource provisioning, or makes SDK calls, I have run the PR checks with the `run-e2e` label set.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-03-01 17:44 UTC, edwardfoyle commented on .changeset/late-ducks-impress.md
> +'@aws-amplify/backend-cli': minor
Doesn't really matter, but this should be a patch, not a minor
```suggestion
'@aws-amplify/backend-cli': patch
```

2024-03-01 18:22 UTC, Amplifiyer requested changes
Instead of this, shouldn't we follow the CDK model and update our supported node versions. If CDK doesn't work with node 21, we won't be able to fix customer issues anyways.

I'm fine with suppressing this warning, but we should replace it with our own warning if customer's node version is outside of amplify's supported versions.

2024-03-01 18:26 UTC, sobolk commented
I 100% agree with @Amplifiyer . Hiding compatibility warnings is counter productive to debugabbility. 

> I'm fine with suppressing this warning, but we should replace it with our own warning if customer's node version is outside of amplify's supported versions.

If we do this we should also establish mechanism to track CDK supported Node, so that we proactively make changes on our side. Therefore my recommendation is to "do nothing" at this time.

2024-03-01 18:39 UTC, ykethan commented
> Instead of this, shouldn't we follow the CDK model and update our supported node versions. If CDK doesn't work with node 21, we won't be able to fix customer issues anyways.
> 
> I'm fine with suppressing this warning, but we should replace it with our own warning if customer's node version is outside of amplify's supported versions.

I was thinking if this can be a callout on the create flow but a warning in a information output/command doesn't feel like great DX tho

2024-03-01 18:44 UTC, Amplifiyer commented
> I was thinking if this can be a callout on the create flow/sandbox but a warning in a informational output/command doesn't feel like great DX tho

Customers can always change their node version after the create-amplify flow, or use a different version of node in their CI/CD pipeline. This is an ideal DX for developers in my opinion to warn them when they are using unsupported runtime.

2024-03-01 21:34 UTC, josefaidt commented
Is this message suppressed anywhere else? It feels odd that it creeps up here, which while it's an important message and folks should be aware, it's clogging the output of what we care about which is the AWS environment variables. CDK rightfully obfuscates sensitive values which was one of the motivations for using CDK to read these values. imo it does not provide a ton of value in `info` output in its current place.

Would it be better if this was lifted to the beginning or end of the output instead of interweaved in the env info?

2024-03-01 21:35 UTC, josefaidt commented
It's also not entirely clear that this message is from CDK, not Amplify. Additionally, node version is already captured towards the top of the output.

2024-03-01 22:16 UTC, edwardfoyle commented
My 2c: suppress this warning in `info` output and add a warning that gets printed as the first line when running any `amplify` or `create-amplify` command with an unsupported node version

2024-03-01 22:57 UTC, josefaidt commented
> My 2c: suppress this warning in info output and add a warning that gets printed as the first line when running any amplify or create-amplify command with an unsupported node version

agreed

> And then do we need our own environment variable like AMPLIFY_SUPPRESS_UNSUPPORTED_NODE_VERSION_WARNING...?

oh goodness, could this be controlled by the log level?

2024-03-02 01:48 UTC, josefaidt commented
can we add an upper bound on the existing `packages.json#engines` key to align with CDK's requirements? https://github.com/aws-amplify/amplify-backend/blob/main/packages/cli/package.json#L23

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

this should print the node version warning

2024-03-04 18:45 UTC, edwardfoyle commented
> can we add an upper bound on the existing packages.json#engines key to align with CDK's requirements?

That would print a warning when installing, but would not print a warning after that. However, since we are suppressing installation output in `create-amplify` customers would not see it.

2024-03-05 00:42 UTC, josefaidt commented
that is a good callout. You'd only see it in the pipeline or on the next clone + setup. With the addition of `amplify check`, could we move it there (without the obnoxious `!!!...`)? Ideally this is a command that is part of your PR checklist

2024-03-06 21:45 UTC, Amplifiyer commented
Just confirmed that `sandbox` also doesn't show this warning along with `create-amplify`.  @ykethan is creating github issues to look into surfacing runtime compatibility warnings for those two commands.

Since currently this seems to be the only place where this warning is surfacing, I'd say let's wait to have this (or our own) warning in the sandbox/create-amplify or pipeline-deploy commands before removing it from the `info` command.

2025-05-05 18:20 UTC, closed without merging