repo readme update
aws-amplify/amplify-backend pull request #1424
Opened 2024-05-01 19:24 UTC by edwardfoyle

Updates the repo readme to remove preview wording

2024-05-01 21:02 UTC, swaminator commented on README.md
> +This next generation of Amplify’s backend building experience lets you author your frontend and backend definition completely with TypeScript, a file convention, and Git branch-based environments. To
docs.amplify.aws

2024-05-01 21:03 UTC, swaminator commented on README.md
> +To get started with Amplify Gen 2, visit [AWS Amplify Gen 2 Quickstart](https://docs.amplify.aws/gen2/start/quickstart/).
https://docs.amplify.aws/react/start/

2024-05-01 21:03 UTC, swaminator commented on README.md
> +## Tutorials
Remove this section.

2024-05-01 21:04 UTC, swaminator requested changes
Comments inline.

2024-05-01 21:36 UTC, edwardfoyle commented on README.md
> +This next generation of Amplify’s backend building experience lets you author your frontend and backend definition completely with TypeScript, a file convention, and Git branch-based environments. To
```suggestion
This next generation of Amplify’s backend building experience lets you author your frontend and backend definition completely with TypeScript, a file convention, and Git branch-based environments. To learn more, visit [AWS Amplify (Gen 2)](https://docs.amplify.aws).
```

2024-05-01 21:36 UTC, edwardfoyle commented on README.md
> +To get started with Amplify Gen 2, visit [AWS Amplify Gen 2 Quickstart](https://docs.amplify.aws/gen2/start/quickstart/).
```suggestion
To get started with Amplify Gen 2, visit [AWS Amplify Gen 2 Quickstart](https://docs.amplify.aws/react/start).
```

2024-05-01 21:36 UTC, edwardfoyle commented on README.md
> +
```suggestion
```

2024-05-01 21:44 UTC, swaminator approved these changes
LGTM

2024-05-06 16:35 UTC, 0618 approved these changes

2024-05-06 16:47 UTC, merged