fix mfa mapping
aws-amplify/amplify-backend pull request #1652
Opened 2024-06-14 16:13 UTC by josefaidt

## Problem

valid MFA configuration values are back and forth across implementations
- the CloudFormation `UserPool` resource accepts `"OFF" | "OPTIONAL" | "ON"` https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-mfaconfiguration
- the L1 `CfnUserPool` construct sets this property to a `string` https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.CfnUserPool.html#mfaconfiguration-1
- the L2 `UserPool` construct accepts `"OFF" | "OPTIONAL" | "REQUIRED"`https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.Mfa.html#members
- the Cognito console alludes to `"no mfa" | "optional" | "required"`
![image](https://github.com/aws-amplify/amplify-backend/assets/5033303/9d02344c-330e-4cc4-a0cb-37e51fecdc7a)

and our unified schema is looking for `"NONE" | "OPTIONAL" | "REQUIRED"`
https://github.com/aws-amplify/amplify-backend/blob/main/packages/client-config/src/client-config-schema/schema_v1.json#L178

This PR aims to narrow the output types to their expected values, update client config generator to map CFN values to the new values, and update legacy convertors to map back down to the CFN values

**Issue number, if available:**

## Changes

**Corresponding docs PR, if applicable:**

## Validation

## Checklist

- [ ] If this PR includes a functional change to the runtime behavior of the code, I have added or updated automated test coverage for this change.
- [ ] If this PR requires a change to the [Project Architecture README](../PROJECT_ARCHITECTURE.md), I have included that update in this PR.
- [ ] If this PR requires a docs update, I have linked to that docs PR above.
- [ ] If this PR modifies E2E tests, makes changes to resource provisioning, or makes SDK calls, I have run the PR checks with the `run-e2e` label set.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-06-19 19:12 UTC, edwardfoyle requested changes
Before we do this we need to complete https://github.com/aws-amplify/amplify-backend/issues/1633 to ensure that this is not introducing a breaking change

2024-06-21 17:52 UTC, sobolk commented
> Before we do this we need to complete #1633 to ensure that this is not introducing a breaking change

@edwardfoyle I was chatting with @josefaidt to trim this PR to just introduce correct mapping in `client-config` which should make concern about "producing" outputs away for now.
Does this help pushing the fix forward?

2024-06-21 18:05 UTC, josefaidt commented
@sobolk @edwardfoyle I've removed the type narrowing from the construct's outputs

2024-06-21 18:07 UTC, sobolk reviewed
LGTM. we need tests.

2024-06-21 18:07 UTC, sobolk commented on packages/client-config/src/client-config-contributor/client_config_contributor_v1.ts
> +      switch (authOutput.payload.mfaConfiguration) {
these two switches should get unit test coverage.

2024-06-21 23:36 UTC, sobolk approved these changes

2024-06-24 17:38 UTC, sobolk approved these changes

2024-06-24 23:17 UTC, edwardfoyle approved these changes

2024-06-24 23:18 UTC, merged