refactor: improved placeholders for error messages
aws-amplify/amplify-backend pull request #1779
Opened 2024-07-24 12:15 UTC by fossamagna

## Problem

**Issue number, if available:**

#1271 

## Changes

**Corresponding docs PR, if applicable:**

## Validation

## Checklist

- [ ] If this PR includes a functional change to the runtime behavior of the code, I have added or updated automated test coverage for this change.
- [ ] If this PR requires a change to the [Project Architecture README](../PROJECT_ARCHITECTURE.md), I have included that update in this PR.
- [ ] If this PR requires a docs update, I have linked to that docs PR above.
- [ ] If this PR modifies E2E tests, makes changes to resource provisioning, or makes SDK calls, I have run the PR checks with the `run-e2e` label set.

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

2024-07-25 19:31 UTC, Amplifiyer approved these changes

2024-07-25 19:32 UTC, Amplifiyer requested changes

2024-07-25 19:32 UTC, Amplifiyer commented on .changeset/gold-tips-film.md
> +---
```suggestion
---
'@aws-amplify/backend-deployer': patch
---

improve placeholders for cdk error messages
```

2024-07-25 19:58 UTC, awsluja approved these changes

2024-07-25 19:59 UTC, awsluja requested changes
Looks good , just need to add the changeset suggested by @Amplifiyer

2024-07-26 00:42 UTC, fossamagna commented
@Amplifiyer @awsluja
Thank you for your review and suggestion.

2024-07-26 12:29 UTC, Amplifiyer commented
Thanks @fossamagna, please merge from main to make the github checks happy. We can then merge this.

2024-07-26 13:58 UTC, fossamagna commented
@Amplifiyer I merged from main. Thanks.

2024-07-26 14:01 UTC, Amplifiyer approved these changes

2024-07-26 14:16 UTC, sobolk approved these changes

2024-07-26 14:24 UTC, merged